import { BannerConfig, DEFAULT_CONFIG } from "./types";

export type Preset = BannerConfig & { id: string; name: string };

export const presets: Preset[] = [
  {
    ...DEFAULT_CONFIG,
    id: "github-default",
    name: "GitHub Dark",
    title: "Hey! I am ...",
    subtitle: "Fullstack developer",
    bgColor: "#161b22",
    titleColor: "#f0f6fc",
    subtitleColor: "#8b949e",
    pattern: "github-pattern",
    patternColor: "#ffffff",
    patternOpacity: 0.06,
    decoration: "octocat",
    decorationOpacity: 0.85,
    decorationSize: 140,
    titleFont: "Red Hat Display",
    subtitleFont: "Red Hat Display",
  },
  {
    ...DEFAULT_CONFIG,
    id: "cyber-blue",
    name: "Cyber Blue",
    title: "build / break / repeat",
    subtitle: "Systems engineer",
    bgColor: "#0d1117",
    titleColor: "#58a6ff",
    subtitleColor: "#79c0ff",
    pattern: "circuit-board",
    patternColor: "#58a6ff",
    patternOpacity: 0.18,
    decoration: "code-brackets",
    decorationSize: 130,
    decorationOpacity: 0.7,
    titleFont: "JetBrains Mono",
    subtitleFont: "JetBrains Mono",
    titleSize: 38,
  },
  {
    ...DEFAULT_CONFIG,
    id: "constellation",
    name: "Constellation",
    title: "shipping to the stars",
    subtitle: "Indie hacker · designer",
    bgColor: "#1a1b27",
    titleColor: "#a9fef7",
    subtitleColor: "#c0caf5",
    pattern: "endless-constellation",
    patternColor: "#a9fef7",
    patternOpacity: 0.22,
    decoration: "rocket",
    decorationSize: 150,
    decorationOpacity: 0.9,
    titleFont: "Orbitron",
    subtitleFont: "Raleway",
  },
  {
    ...DEFAULT_CONFIG,
    id: "topography",
    name: "Topography",
    title: "exploring the stack",
    subtitle: "Site reliability · open source",
    bgColor: "#2d333b",
    titleColor: "#cdd9e5",
    subtitleColor: "#909dab",
    pattern: "topography",
    patternColor: "#ffffff",
    patternOpacity: 0.1,
    decoration: null,
    titleFont: "Maven Pro",
    subtitleFont: "Maven Pro",
  },
  {
    ...DEFAULT_CONFIG,
    id: "terminal-bubbles",
    name: "Terminal Bubbles",
    title: "$ whoami",
    subtitle: "Backend · distributed systems",
    bgColor: "#0f0e17",
    titleColor: "#fffffe",
    subtitleColor: "#a7a9be",
    pattern: "bubbles",
    patternColor: "#ff8906",
    patternOpacity: 0.35,
    decoration: "terminal",
    decorationSize: 120,
    decorationOpacity: 0.85,
    titleFont: "Source Code Pro",
    subtitleFont: "Source Code Pro",
    titleSize: 44,
  },
  {
    ...DEFAULT_CONFIG,
    id: "catppuccin",
    name: "Catppuccin",
    title: "soft / warm / focused",
    subtitle: "Design engineer",
    bgColor: "#1e1e2e",
    titleColor: "#cba6f7",
    subtitleColor: "#f5c2e7",
    pattern: "honeycomb",
    patternColor: "#cba6f7",
    patternOpacity: 0.18,
    decoration: "atom",
    decorationSize: 130,
    decorationOpacity: 0.6,
    titleFont: "Poppins",
    subtitleFont: "Poppins",
  },
  {
    ...DEFAULT_CONFIG,
    id: "dracula",
    name: "Dracula",
    title: "// always coding",
    subtitle: "Open source maintainer",
    bgColor: "#282a36",
    titleColor: "#50fa7b",
    subtitleColor: "#bd93f9",
    pattern: "graph-paper",
    patternColor: "#bd93f9",
    patternOpacity: 0.3,
    decoration: "lightning",
    decorationSize: 140,
    decorationOpacity: 0.8,
    titleFont: "Fira Code",
    subtitleFont: "Fira Code",
  },
  {
    ...DEFAULT_CONFIG,
    id: "nord",
    name: "Nord",
    title: "calm. clear. shipped.",
    subtitle: "Platform engineer",
    bgColor: "#2e3440",
    titleColor: "#88c0d0",
    subtitleColor: "#d8dee9",
    pattern: "honeycomb",
    patternColor: "#88c0d0",
    patternOpacity: 0.15,
    decoration: "cube",
    decorationSize: 130,
    decorationOpacity: 0.6,
    titleFont: "Josefin Sans",
    subtitleFont: "Josefin Sans",
  },
  {
    ...DEFAULT_CONFIG,
    id: "github-light",
    name: "GitHub Light",
    title: "Hey, nice to meet you.",
    subtitle: "Software engineer",
    bgColor: "#ffffff",
    titleColor: "#1f2328",
    subtitleColor: "#656d76",
    pattern: null,
    decoration: "github-mark",
    decorationSize: 140,
    decorationOpacity: 0.18,
    borderColor: "#d0d7de",
    borderWidth: 1,
    titleFont: "Red Hat Display",
    subtitleFont: "Red Hat Display",
  },
  {
    ...DEFAULT_CONFIG,
    id: "hacker",
    name: "Hacker",
    title: "> root@matrix:~#",
    subtitle: "Security researcher",
    bgColor: "#0a0a0a",
    titleColor: "#39ff14",
    subtitleColor: "#39ff14",
    pattern: "circuit-board",
    patternColor: "#39ff14",
    patternOpacity: 0.18,
    decoration: "terminal-circle",
    decorationSize: 140,
    decorationOpacity: 0.8,
    titleFont: "Anonymous Pro",
    subtitleFont: "Anonymous Pro",
    titleSize: 36,
    subtitleSize: 18,
  },
  {
    ...DEFAULT_CONFIG,
    id: "tokyo-night",
    name: "Tokyo Night",
    title: "neon dreams",
    subtitle: "Frontend · motion · WebGL",
    bgColor: "#1f2335",
    titleColor: "#7aa2f7",
    subtitleColor: "#bb9af7",
    pattern: "falling-triangles",
    patternColor: "#7aa2f7",
    patternOpacity: 0.22,
    decoration: "rocket",
    decorationSize: 130,
    decorationOpacity: 0.85,
    titleFont: "Exo 2",
    subtitleFont: "Exo 2",
    titleSize: 46,
  },
  {
    ...DEFAULT_CONFIG,
    id: "solarized",
    name: "Solarized",
    title: "Hello, world.",
    subtitle: "Tinkerer · writer · cyclist",
    bgColor: "#fdf6e3",
    titleColor: "#268bd2",
    subtitleColor: "#657b83",
    pattern: "stamp-collection",
    patternColor: "#586e75",
    patternOpacity: 0.4,
    decoration: "idea-bulb",
    decorationSize: 130,
    decorationOpacity: 0.5,
    borderColor: "#eee8d5",
    borderWidth: 1,
    titleFont: "Quattrocento",
    subtitleFont: "Quattrocento",
  },
  {
    ...DEFAULT_CONFIG,
    id: "synthwave",
    name: "Synthwave",
    title: "from the grid",
    subtitle: "Game dev · WebGL · shaders",
    bgColor: "#241b2f",
    titleColor: "#ff7edb",
    subtitleColor: "#36f9f6",
    pattern: "graph-paper",
    patternColor: "#ff7edb",
    patternOpacity: 0.28,
    decoration: "controller",
    decorationSize: 140,
    decorationOpacity: 0.85,
    titleFont: "Orbitron",
    subtitleFont: "Electrolize",
    titleSize: 44,
  },
  {
    ...DEFAULT_CONFIG,
    id: "sunset",
    name: "Sunset",
    title: "shipping with sunshine",
    subtitle: "Mobile · iOS · Swift",
    bgColor: "#ff9966",
    titleColor: "#ffffff",
    subtitleColor: "#fff5e6",
    pattern: "endless-clouds",
    patternColor: "#ffffff",
    patternOpacity: 0.35,
    decoration: "cloud",
    decorationSize: 150,
    decorationOpacity: 0.55,
    titleFont: "Bebas Neue",
    subtitleFont: "Raleway",
    titleSize: 50,
  },
  {
    ...DEFAULT_CONFIG,
    id: "monochrome",
    name: "Monochrome",
    title: "less, but better.",
    subtitle: "Design systems · typography",
    bgColor: "#0a0a0a",
    titleColor: "#fafafa",
    subtitleColor: "#a3a3a3",
    pattern: null,
    decoration: "diamond",
    decorationSize: 130,
    decorationOpacity: 0.6,
    borderColor: "#262626",
    borderWidth: 1,
    titleFont: "Cinzel",
    subtitleFont: "Raleway",
    titleSize: 46,
  },
  {
    ...DEFAULT_CONFIG,
    id: "matrix",
    name: "Matrix",
    title: "wake up, neo.",
    subtitle: "Backend · OS · low-level",
    bgColor: "#000000",
    titleColor: "#00ff41",
    subtitleColor: "#00cc33",
    pattern: "lisbon",
    patternColor: "#00ff41",
    patternOpacity: 0.18,
    decoration: "terminal-circle",
    decorationSize: 140,
    decorationOpacity: 0.8,
    titleFont: "Source Code Pro",
    subtitleFont: "Source Code Pro",
    titleSize: 42,
  },
  {
    ...DEFAULT_CONFIG,
    id: "ocean",
    name: "Ocean",
    title: "deep work, deep stack.",
    subtitle: "Cloud · Kubernetes · Go",
    bgColor: "#003049",
    titleColor: "#fdf0d5",
    subtitleColor: "#669bbc",
    pattern: "topography",
    patternColor: "#669bbc",
    patternOpacity: 0.3,
    decoration: "globe",
    decorationSize: 140,
    decorationOpacity: 0.7,
    titleFont: "Maven Pro",
    subtitleFont: "Maven Pro",
  },
  {
    ...DEFAULT_CONFIG,
    id: "blueprint",
    name: "Blueprint",
    title: "from sketch to ship",
    subtitle: "Architect · designer · builder",
    bgColor: "#0d3b66",
    titleColor: "#faf0ca",
    subtitleColor: "#f4d35e",
    pattern: "graph-paper",
    patternColor: "#faf0ca",
    patternOpacity: 0.2,
    decoration: "pencil",
    decorationSize: 130,
    decorationOpacity: 0.7,
    titleFont: "Quattrocento",
    subtitleFont: "Quattrocento",
  },
  {
    ...DEFAULT_CONFIG,
    id: "rose-gold",
    name: "Rose Gold",
    title: "details matter",
    subtitle: "Brand · product · craft",
    bgColor: "#fff1e6",
    titleColor: "#9d3c62",
    subtitleColor: "#b8627a",
    pattern: "moroccan",
    patternColor: "#9d3c62",
    patternOpacity: 0.18,
    decoration: "heart",
    decorationSize: 120,
    decorationOpacity: 0.4,
    borderColor: "#f3d6c6",
    borderWidth: 1,
    titleFont: "Playball",
    subtitleFont: "Raleway",
    titleSize: 50,
  },
  {
    ...DEFAULT_CONFIG,
    id: "forest",
    name: "Forest",
    title: "growing in public",
    subtitle: "Indie maker · slow software",
    bgColor: "#1b4332",
    titleColor: "#d8f3dc",
    subtitleColor: "#95d5b2",
    pattern: "leaf",
    patternColor: "#95d5b2",
    patternOpacity: 0.25,
    decoration: "shield",
    decorationSize: 130,
    decorationOpacity: 0.5,
    titleFont: "Josefin Sans",
    subtitleFont: "Josefin Sans",
  },
  {
    ...DEFAULT_CONFIG,
    id: "vapor",
    name: "Vapor",
    title: "未来 · the future",
    subtitle: "Frontend · 3D · creative dev",
    bgColor: "#2d1b69",
    titleColor: "#ffd6ff",
    subtitleColor: "#bbd0ff",
    pattern: "endless-constellation",
    patternColor: "#ffd6ff",
    patternOpacity: 0.3,
    decoration: "planet",
    decorationSize: 150,
    decorationOpacity: 0.85,
    titleFont: "Exo 2",
    subtitleFont: "Exo 2",
    titleSize: 48,
  },
  {
    ...DEFAULT_CONFIG,
    id: "paper",
    name: "Paper",
    title: "Just shipping.",
    subtitle: "@yourname · github.com/yourname",
    bgColor: "#fafafa",
    titleColor: "#171717",
    subtitleColor: "#737373",
    pattern: "topography",
    patternColor: "#171717",
    patternOpacity: 0.05,
    decoration: "pencil",
    decorationSize: 110,
    decorationOpacity: 0.35,
    borderColor: "#e5e5e5",
    borderWidth: 1,
    titleFont: "Della Respira",
    subtitleFont: "Anonymous Pro",
    titleSize: 44,
  },
  {
    ...DEFAULT_CONFIG,
    id: "honey",
    name: "Honey",
    title: "build sweet things",
    subtitle: "Open source · community",
    bgColor: "#fcbf49",
    titleColor: "#003049",
    subtitleColor: "#003049",
    pattern: "honeycomb",
    patternColor: "#003049",
    patternOpacity: 0.15,
    decoration: "star",
    decorationSize: 130,
    decorationOpacity: 0.4,
    titleFont: "Bebas Neue",
    subtitleFont: "Raleway",
    titleSize: 52,
  },
  {
    ...DEFAULT_CONFIG,
    id: "midnight-data",
    name: "Midnight Data",
    title: "queries at 3am",
    subtitle: "Data engineer · ML · analytics",
    bgColor: "#0f172a",
    titleColor: "#38bdf8",
    subtitleColor: "#94a3b8",
    pattern: "circuit-board",
    patternColor: "#38bdf8",
    patternOpacity: 0.18,
    decoration: "database",
    decorationSize: 140,
    decorationOpacity: 0.8,
    titleFont: "JetBrains Mono",
    subtitleFont: "JetBrains Mono",
    titleSize: 38,
  },
  {
    ...DEFAULT_CONFIG,
    id: "espresso",
    name: "Espresso",
    title: "powered by coffee",
    subtitle: "Fullstack · always shipping",
    bgColor: "#3e2723",
    titleColor: "#fbe9e7",
    subtitleColor: "#d7ccc8",
    pattern: "dalmatian-spots",
    patternColor: "#d7ccc8",
    patternOpacity: 0.18,
    decoration: "coffee",
    decorationSize: 140,
    decorationOpacity: 0.85,
    titleFont: "Lancelot",
    subtitleFont: "Quattrocento",
    titleSize: 48,
  },
  {
    ...DEFAULT_CONFIG,
    id: "candy",
    name: "Candy Pop",
    title: "playground for ideas",
    subtitle: "Designer · creative coder",
    bgColor: "#ff5d8f",
    titleColor: "#ffffff",
    subtitleColor: "#fff0f6",
    pattern: "bubbles",
    patternColor: "#ffffff",
    patternOpacity: 0.4,
    decoration: "smile-cat",
    decorationSize: 140,
    decorationOpacity: 0.75,
    titleFont: "Pixelify Sans",
    subtitleFont: "Poppins",
    titleSize: 44,
  },
  {
    ...DEFAULT_CONFIG,
    id: "sketch",
    name: "Sketchbook",
    title: "always learning.",
    subtitle: "Student · curious · building",
    bgColor: "#fffaf0",
    titleColor: "#1a1a1a",
    subtitleColor: "#525252",
    pattern: "charlie-brown",
    patternColor: "#1a1a1a",
    patternOpacity: 0.2,
    decoration: "book",
    decorationSize: 130,
    decorationOpacity: 0.5,
    borderColor: "#e7e5e4",
    borderWidth: 2,
    titleFont: "Kalam",
    subtitleFont: "Kalam",
    titleSize: 46,
  },
  {
    ...DEFAULT_CONFIG,
    id: "gamer",
    name: "Player One",
    title: "press start to begin",
    subtitle: "Game dev · pixel art",
    bgColor: "#1a1a2e",
    titleColor: "#e94560",
    subtitleColor: "#f5f5f5",
    pattern: "squares",
    patternColor: "#e94560",
    patternOpacity: 0.18,
    decoration: "pixel-heart",
    decorationSize: 130,
    decorationOpacity: 0.85,
    titleFont: "Pixelify Sans",
    subtitleFont: "Pixelify Sans",
    titleSize: 44,
  },
  {
    ...DEFAULT_CONFIG,
    id: "gradient-night",
    name: "Aurora",
    title: "crafted in motion",
    subtitle: "Animator · Framer · After Effects",
    bgColor: "#16161e",
    titleColor: "#a3e635",
    subtitleColor: "#67e8f9",
    pattern: "overlapping-circles",
    patternColor: "#a3e635",
    patternOpacity: 0.18,
    decoration: "sound-wave",
    decorationSize: 140,
    decorationOpacity: 0.7,
    titleFont: "Passero One",
    subtitleFont: "Athiti",
    titleSize: 48,
  },
];
