import { nanoid } from "./nanoid.js";
import type { BannerParams, TextLayer } from "./types.js";

export function createDefaultTextLayer(overrides: Partial<TextLayer> = {}): TextLayer {
  return {
    id: nanoid(),
    text: "Hello, World",
    fontFamily: "Poppins",
    fontSize: 64,
    fontWeight: 700,
    fontStyle: "normal",
    fontColor: "#ffffff",
    fontAlign: "center",
    alignX: 50,
    alignY: 50,
    letterSpacing: 0,
    textTransform: "none",
    textDecoration: "none",
    rotate: 0,
    opacity: 1,
    gradient: false,
    gradientColors: ["#ffffff", "#a0c4ff"],
    textShadow: false,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowX: 0,
    textShadowY: 4,
    textShadowBlur: 8,
    glowEffect: false,
    glowColor: "#ffffff",
    glowRadius: 8,
    textStroke: false,
    textStrokeColor: "#000000",
    textStrokeWidth: 2,
    animation: "none",
    animationDelay: 0,
    ...overrides,
  };
}

export const DEFAULT_PARAMS: BannerParams = {
  type: "waving",
  width: 1200,
  height: 280,
  color: "#0072ff",
  colorPreset: "ocean",
  gradientType: "linear",
  gradientAngle: 90,
  gradientStops: [
    { color: "#0072ff", position: 0 },
    { color: "#00c6ff", position: 50 },
    { color: "#0072ff", position: 100 },
  ],
  reverseColor: false,
  pattern: "none",
  patternColor: "#ffffff",
  patternOpacity: 0.15,
  patternScale: 1,
  particles: "none",
  particleCount: 30,
  particleColor: "#ffffff",
  particleSize: 4,
  particleOpacity: 0.8,
  overlay: "none",
  overlayOpacity: 0.4,
  overlayColor: "#000000",
  blur: 0,
  shadow: "none",
  brightness: 1,
  contrast: 1,
  saturation: 1,
  hueRotate: 0,
  animationSpeed: 1,
  textLayers: [
    createDefaultTextLayer({
      text: "BannerForge",
      fontFamily: "Poppins",
      fontSize: 80,
      fontWeight: 800,
      animation: "fadeIn",
    }),
    createDefaultTextLayer({
      text: "GitHub README banner generator",
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 500,
      alignY: 72,
      opacity: 0.9,
      animation: "slideInBottom",
      animationDelay: 200,
    }),
  ],
};
